### ISSUE TITLE
Specify license of docs

### ISSUE THREAD

**Issue by ian-kelling** [dae/ankidocs#22]
Imo, using same as anki, cc-by, cc-by-sa or gfdl are all good options.

**Comment by dae** [comment]
sorry, this fell off my radar - I'll get back to you in a few days

**Comment by dae** [comment]
ok, I've specified cc-by-sa and added a license file to the repo, thanks. I hadn't intended to leave github issues on this repo, so I'll close it down now - if you need to discuss this further please let us know on the support site
